[profile.default]
src = "src"
out = "out"
libs = ["lib"]

bracket_spacing = true
wrap_comments = true
line_length = 120
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
